language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

branches:
  except:
    - gh-pages

addons:
  hosts:
    - blank
  chrome: stable

sudo: false

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer install

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
